use	libreria_23508;


SELECT *
FROM libreria_23508.AUTOR;

SELECT *
FROM libreria_23508.VENTA;

SELECT *
FROM libreria_23508.LINK_AUTOR_LIBRO;


-- CRUD  => CREATE | READ(RETRIEVE) |  UPDATE | DELETE
-- CREAR
INSERT INTO libreria_23508.AUTOR
VALUES
(22,'Walter');

-- LECTURA
SELECT 
	ISBN
,	EDITORIAL
,	TITULO

FROM libreria_23508.LIBRO
WHERE 
	EDITORIAL LIKE 'Comedy%'
;


-- ACTUALIZAR
UPDATE libreria_23508.AUTOR
SET NOMBRE = 'Dracula'
WHERE NOMBRE LIKE 'Vladamir';

SELECT * 
FROM libreria_23508.VENTA
WHERE TRUE
AND FECHA_VENTA >= '1995-02-10';

UPDATE libreria_23508.VENTA
SET PUNTO_VENTA = 'Palermo Queen'
WHERE TRUE
AND YEAR(FECHA_VENTA) >= 1995
AND PRECIO_VENTA >= 300;

-- BORRAR
DELETE FROM libreria_23508.AUTOR
WHERE TRUE
AND NOMBRE LIKE 'D%';

DELETE FROM libreria_23508.AUTOR
WHERE TRUE
AND CODIGO_AUTOR = 22;

SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM libreria_23508.AUTOR
WHERE NOMBRE LIKE 'G%';

DELETE FROM libreria_23508.AUTOR 
;



-- PEDIDOS DESDE EL AREA (yo_andru)

	-- TOTAL DE CANTIDAD DE VENTAS POR AÑO
	-- LIBRO CON MAYOR CANTIDAD DE VENTAS
	-- DADO EL MODELO QUIERO SABER QUIENES COMPRARON EN EL ULTIMO AÑO
	-- CANTIDAD DE LIBROS POR AUTOR

-- CANTIDAD DE VENTAS POR AÑO 
-- TOTAL DE VENTAS POR AÑO

SELECT 
	*
FROM libreria_23508.VENTA
    LIMIT 10;

SELECT 
		YEAR(FECHA_VENTA) AS ANIO
	,	COUNT(1) AS CANTIDAD_VENTAS

FROM libreria_23508.VENTA
GROUP BY YEAR(FECHA_VENTA) -- ANIO
	HAVING COUNT(1) > 6
ORDER BY CANTIDAD_VENTAS DESC 
;



	SELECT
	
		YEAR(FECHA_VENTA) AS ANIO
	,	COUNT(1) AS CANTIDAD_VENTAS
    
	FROM libreria_23508.VENTA
	GROUP BY YEAR(FECHA_VENTA)
    ORDER BY ANIO DESC
    ;
    
    
    
	SELECT 
		YEAR(FECHA_VENTA) AS ANIO
	,	SUM(PRECIO_VENTA) AS TOTAL_VENTA

	FROM libreria_23508.VENTA
	GROUP BY YEAR(FECHA_VENTA)
	ORDER BY TOTAL_VENTA DESC
	;



    -- LIBRO CON MAYOR CANTIDAD DE VENTAS
    
-- SUBQUERY    
	SELECT 
		CODIGO_EJEMPLAR
    FROM	
    (
		SELECT 
			CODIGO_EJEMPLAR
		,	COUNT(1) AS CANT_VENTA

		FROM libreria_23508.VENTA
		GROUP BY CODIGO_EJEMPLAR
		ORDER BY CANT_VENTA DESC
		LIMIT 1
    ) 
   AS SUB ;

 -- ------------------------------------------------
 
SELECT * 
FROM libreria_23508.EJEMPLAR;

SELECT 
	-- CODIGO_LIBRO
    *
FROM libreria_23508.EJEMPLAR
	WHERE 
    CODIGO_EJEMPLAR = 
		(	SELECT 
			CODIGO_EJEMPLAR
			FROM	
				(
					SELECT 
						CODIGO_EJEMPLAR
					,	COUNT(1) AS CANT_VENTA

					FROM libreria_23508.VENTA
					GROUP BY CODIGO_EJEMPLAR
					ORDER BY CANT_VENTA DESC
					LIMIT 1
				) AS SUB 
);


-- CUAL ES EL LIBRO 45 ?  VEAMOS EN LA TABLA LIBRO
SELECT *
FROM libreria_23508.LIBRO;

-- PODRIAMOS USAR UN EXISTS
SELECT 
    *
FROM libreria_23508.LIBRO AS l
WHERE EXISTS
(
		SELECT 
			CODIGO_LIBRO
		FROM libreria_23508.EJEMPLAR AS e
			WHERE 
			CODIGO_EJEMPLAR = 
				(	SELECT 
					CODIGO_EJEMPLAR
				FROM	
				(
				SELECT 
					CODIGO_EJEMPLAR
				,	COUNT(1) AS CANT_VENTA

				FROM libreria_23508.VENTA
				GROUP BY CODIGO_EJEMPLAR
				ORDER BY CANT_VENTA DESC
				LIMIT 1
				) AS SUB 
			) 
            AND 
            CODIGO_LIBRO = l.CODIGO_LIBRO
);


-- DADO EL MODELO QUIERO SABER LOS USUARIOS QUE COMPRARON EN EL ULTIMO AÑO

SELECT 
	*
	FROM (SELECT 
			ID_USUARIO
		,	YEAR(FECHA_VENTA) as ANIO
	FROM libreria_23508.VENTA
	) AS uf

ORDER BY ANIO DESC;

-- LIBROS POR AUTOR
-- JOINS


SELECT *
FROM libreria_23508.LINK_AUTOR_LIBRO;

SELECT 
		a.NOMBRE
	,	link.CODIGO_LIBRO
	,	l.TITULO
FROM libreria_23508.AUTOR AS a
LEFT JOIN libreria_23508.LINK_AUTOR_LIBRO AS link
ON a.CODIGO_AUTOR = link.CODIGO_AUTOR 

LEFT JOIN libreria_23508.LIBRO as l
ON link.CODIGO_LIBRO = l.CODIGO_LIBRO;
