FROM ubuntu:latest

WORKDIR /project

RUN apt update -y && apt upgrade -y && apt  install git -y && apt install nano -y

#	STEPS
#	docker build --tag ubuntu .
#	docker run  --name local_ubuntu -v ./project:/project -d -it ubuntu
#	docker exec -it local_ubuntu bash
