# Generated by Django 4.2.7 on 2023-11-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="Tienda x", max_length=100)),
                ("rubro", models.CharField(default="rubro x", max_length=100)),
                (
                    "contacto",
                    models.EmailField(default="no_contact@mail.com", max_length=100),
                ),
                (
                    "ubicacion",
                    models.CharField(default="Tienda online", max_length=100),
                ),
                ("fecha_habilitacion", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "tiendas_buenos_aires_arg",
            },
        ),
    ]
